name: cash_records
description: An app for maintaining cash records

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.1.0
  printing: ^5.0.4
  pdf: ^3.1.0
  intl: ^0.17.0
  path_provider: any
  open_file: ^3.1.0
  file_picker: ^3.0.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.13.2
  hive: ^2.0.4
  share: ^2.0.4
  google_fonts: ^2.1.0
  in_app_review: ^2.0.2
  url_launcher: ^6.0.9
  googleapis: ^2.0.0
  google_sign_in: ^5.0.1
  googleapis_auth: ^1.1.0
  archive: ^3.1.2
  flutter_styled_toast: ^2.0.0
  flutter_web_browser: ^0.14.0
  queue: ^3.1.0
  flutter_inappwebview: ^5.3.2
  move_to_background: ^1.0.2
  in_app_purchase: ^1.0.9
  #esys_flutter_share: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/notosans-regular.ttf
    - assets/notosans-bold.ttf
    - assets/notosans-italic.ttf
    - assets/notosans-boldItalic.ttf
    - assets/currency.xlsx
    - assets/iconNew.png
    - assets/GLogo.jpg